plugin:
  database: jdbc:mysql://127.0.0.1:3306/database
  username: username
  password: password
  bungee: true
  # if 'bungee' is set to true, the plugin will load the data after
  # the player has joined the server, instead of loading on
  # player's pre-login.
  delayInTicks: 30
  # The delay before reading database. If players are often kicked because
  # of locked data, try increasing this value.
  debug: false

sync:
  health: true
  food: true
  exp: true
  inventory: true
  chest: true
  potion: true
<<<<<<< HEAD
=======
  # The delay before read database. If player
  # - "Your data is locked, login later"
  # too often, grow this value. Values by tick.
  delay: 30
>>>>>>> upstream/master

messages:
  dataLoading: "&aPlease wait while your data is being loaded :)"
  dataSynchronized: "&aEnjoy! All your data has been synchronized."