plugin:
  database: jdbc:mysql://127.0.0.1:3306/database
  username: username
  password: password
  debug: false
  messages: false

sync:
  health: true
  food: true
  exp: true
  inventory: true
  chest: true
  potion: true
  # The delay in ticks before reading database. If players are often kicked because
  # of locked data, try increasing this value.
  delay: 30

messages:
  dataLoading: "&aPlease wait while your data is being loaded :)"
  dataSynchronized: "&aEnjoy! All your data has been synchronized."