plugin:
  database: jdbc:mysql://127.0.0.1:3306/database
  username: username
  password: password
  debug: false
  messages: false

sync:
  health: true
  food: true
  exp: true
  inventory: true
  chest: true
  potion: true
  # The delay before read database. If player
  # - "Your data is locked, login later"
  # too often, grow this value. Values by tick.
  delay: 30

messages:
  dataLoading: "&aPlease wait while your data is being loaded :)"
  dataSynchronized: "&aEnjoy! All your data has been synchronized."