plugin:
  database: jdbc:mysql://127.0.0.1:3306/database
  username: username
  password: password
  bungee: true
  # if 'bungee' is set to true, the plugin will load the data after
  # the player has joined the server, instead of loading on
  # player's pre-login.
  debug: false

sync:
  health: true
  food: true
  exp: true
  inventory: true
  chest: true
  potion: true

messages:
  dataLoading: "&aPlease wait while your data is being loaded :)"